name: hackerkegeln
description: A simple console application.
version: 0.0.1
publish_to: none
#homepage: https://www.example.com
#author: dennis <email@example.com>

environment:
  sdk: '>=1.20.1 <2.0.0'

#dependencies:
#  angular2: ^3.0.0-beta

dev_dependencies:
  test: ^0.12.0
  mockito: any
  browser: ^0.10.0
  dart_to_js_script_rewriter: ^1.0.1

transformers:
#- angular2:
#    platform_directives:
#    - 'package:angular2/common.dart#COMMON_DIRECTIVES'
#    platform_pipes:
#    - 'package:angular2/common.dart#COMMON_PIPES'
#    entry_points: web/main.dart
- dart_to_js_script_rewriter